from tts_mos_test_mturk.correlations import get_algorithm_mos_correlations as algorithm_correlation
from tts_mos_test_mturk.correlations import \
  get_sentence_mos_correlations_3dim as sentence_correlation
